const C=window.GOONFX_CONFIG;const $=s=>document.querySelector(s);const api=(p,o={})=>fetch(C.BACKEND_URL+p,{credentials:'include',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});let state={market:'1HZ100V',prices:[],digit:5,type:'DIGITOVER'};
function b64url(b){return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function login(){sessionStorage.removeItem('gx_auto_login_started');const v=new Uint8Array(64);crypto.getRandomValues(v);const a='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';const verifier=Array.from(v,x=>a[x%a.length]).join('');const state=crypto.randomUUID();const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));sessionStorage.setItem('gx_verifier',verifier);sessionStorage.setItem('gx_state',state);sessionStorage.setItem('gx_auto_login_started','1');const u=new URL('https://auth.deriv.com/oauth2/auth');u.search=new URLSearchParams({response_type:'code',client_id:C.DERIV_CLIENT_ID,redirect_uri:C.DERIV_REDIRECT_URI,scope:C.DERIV_SCOPE,state,code_challenge:b64url(new Uint8Array(hash)),code_challenge_method:'S256'});location.assign(u.toString())}
async function callback(){const p=new URLSearchParams(location.search),code=p.get('code'),returned=p.get('state'),err=p.get('error');if(err)throw Error(p.get('error_description')||err);if(!code)return false;const saved=sessionStorage.getItem('gx_state'),verifier=sessionStorage.getItem('gx_verifier');if(!returned||returned!==saved||!verifier)throw Error('OAuth session expired. Start again.');const r=await api('/api/oauth/exchange',{method:'POST',body:JSON.stringify({code,state:returned,code_verifier:verifier,redirect_uri:C.DERIV_REDIRECT_URI,client_id:C.DERIV_CLIENT_ID})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Deriv authorization failed');sessionStorage.removeItem('gx_state');sessionStorage.removeItem('gx_verifier');sessionStorage.removeItem('gx_auto_login_started');history.replaceState({},'',location.pathname);return true}
function showLogin(msg='Redirecting to Deriv…'){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginStatus').textContent=msg}function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden')}
async function account(){const r=await api('/api/accounts');if(!r.ok)return false;const d=await r.json();const xs=d.accounts||[];$('#accountSelect').innerHTML=xs.map(x=>`<option value="${x.account_id}">${x.account_id} · ${x.mode} · ${Number(x.balance||0).toFixed(2)} ${x.currency||''}</option>`).join('');if(d.current){$('#accountSelect').value=d.current.account_id;$('#balance').textContent=`${Number(d.current.balance||0).toFixed(2)} ${d.current.currency||''}`}return true}
async function markets(){try{const r=await api('/api/markets');const d=await r.json();const m=d.markets||[];$('#marketSelect').innerHTML=m.map(x=>`<option value="${x.symbol}">${x.display||x.symbol}</option>`).join('');if(m.length){state.market=m.some(x=>x.symbol===state.market)?state.market:m[0].symbol;$('#marketSelect').value=state.market;$('#marketName').textContent=$('#marketSelect').selectedOptions[0].textContent;await ticks()}}catch(e){}}
async function ticks(){try{const r=await api(`/api/markets/${encodeURIComponent(state.market)}/ticks?count=100`);const d=await r.json();state.prices=(d.prices||[]).map(Number).filter(Number.isFinite);const last=state.prices.at(-1);if(last!=null){$('#livePrice').textContent=last.toFixed(2);$('#tickTime').textContent='Live tick feed'}digits();analysis();}catch(e){$('#tickTime').textContent='Feed unavailable'}}
function digits(){const c=Array(10).fill(0);state.prices.forEach(v=>{const d=Number(String(v).replace(/\D/g,'').at(-1));if(Number.isInteger(d))c[d]++});const t=c.reduce((a,b)=>a+b,0)||1;$('#digits').innerHTML=c.map((n,d)=>`<div class="digit ${d===state.digit?'hot':''}" data-digit="${d}"><b>${d}</b><span>${(n/t*100).toFixed(1)}%</span></div>`).join('');document.querySelectorAll('.digit').forEach(x=>x.onclick=()=>{state.digit=Number(x.dataset.digit);digits()})}
function analysis(){const c=Array(10).fill(0);state.prices.forEach(v=>{const d=Number(String(v).replace(/\D/g,'').at(-1));if(Number.isInteger(d))c[d]++});const t=c.reduce((a,b)=>a+b,0)||1;const even=c.filter((_,i)=>i%2===0).reduce((a,b)=>a+b,0)/t*100;const over=c.slice(6).reduce((a,b)=>a+b,0)/t*100;const hot=c.indexOf(Math.max(...c));$('#analysis').innerHTML=[['Hot digit',hot],['Even',even.toFixed(1)+'%'],['Odd',(100-even).toFixed(1)+'%'],['Over 5',over.toFixed(1)+'%'],['Under 5',(100-over).toFixed(1)+'%']].map(x=>`<div class="analysis-box"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function setup(){if($('#loginBtn'))$('#loginBtn').onclick=()=>login().catch(e=>showLogin(e.message));if($('#logoutBtn'))$('#logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'});sessionStorage.clear();location.reload()};if($('#marketSelect'))$('#marketSelect').onchange=async e=>{state.market=e.target.value;$('#marketName').textContent=e.target.selectedOptions[0].textContent;await ticks()};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.panel+'Panel').classList.remove('hidden')});setInterval(()=>account(),15000);setInterval(()=>ticks(),5000)}
(async()=>{setup();try{const did=await callback();const ok=await account();if(!ok){showLogin('Redirecting to Deriv…');if(!new URLSearchParams(location.search).get('code'))setTimeout(()=>login().catch(e=>showLogin(e.message)),150);return}showApp();await markets();if(did)$('#tradeMessage').textContent='Deriv connected successfully.'}catch(e){sessionStorage.removeItem('gx_auto_login_started');showLogin(e.message)}})();