import quickDigits from './quick-digits.js';
import overUnder from './over-under.js';
import evenOdd from './even-odd.js';
import riseFall from './rise-fall.js';
import accumulator from './accumulator.js';
import ai from './ai.js';
import signalAI from './signal-ai.js';
import apex from './apex.js';
import automated from './automated.js';
import quick from './quick.js';
import crashBoom from './crash-boom.js';
export const BOTS=[quickDigits,overUnder,evenOdd,riseFall,accumulator,ai,signalAI,apex,automated,quick,crashBoom];
